name: Generate Snake
on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@v3
        with:
          github_user_name: Thamaraikannan00011
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
